# Generated by Django 3.1.11 on 2021-05-24 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='details',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='trade',
            name='buyer_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_offer', related_query_name='buyer_offer', to='trade.offer'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='seller_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_offer', related_query_name='seller_offer', to='trade.offer'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('date', models.DateTimeField(blank=True, null=True, unique=True)),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trade.currency')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', related_query_name='prices', to='trade.item')),
            ],
        ),
    ]
