# Generated by Django 3.1.11 on 2021-05-25 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20210524_1913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='entry_quantity',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
    ]
