# Generated by Django 3.1.11 on 2021-05-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0003_auto_20210525_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='item',
        ),
        migrations.AddField(
            model_name='inventory',
            name='item',
            field=models.ManyToManyField(null=True, to='trade.Item'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.ManyToManyField(to='trade.Currency'),
        ),
        migrations.RemoveField(
            model_name='offer',
            name='item',
        ),
        migrations.AddField(
            model_name='offer',
            name='item',
            field=models.ManyToManyField(null=True, to='trade.Item'),
        ),
        migrations.RemoveField(
            model_name='trade',
            name='item',
        ),
        migrations.AddField(
            model_name='trade',
            name='item',
            field=models.ManyToManyField(null=True, to='trade.Item'),
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='item',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='item',
            field=models.ManyToManyField(null=True, to='trade.Item'),
        ),
    ]
