# Generated by Django 3.1.11 on 2021-05-26 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20210526_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='item',
            field=models.ManyToManyField(to='trade.Item'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='trade.currency'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='item',
            field=models.ManyToManyField(to='trade.Item'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='item',
            field=models.ManyToManyField(to='trade.Item'),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='item',
            field=models.ManyToManyField(to='trade.Item'),
        ),
    ]
