# Generated by Django 3.1.11 on 2021-05-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20210526_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.PositiveSmallIntegerField(choices=[('buy', 'BUY'), ('sell', 'SELL')]),
        ),
    ]
