# Generated by Django 3.1.11 on 2021-05-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0007_auto_20210526_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='item',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='unit_price',
        ),
        migrations.AlterField(
            model_name='offer',
            name='order_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'BUY'), (2, 'SELL')]),
        ),
    ]
