# Generated by Django 3.1.11 on 2021-05-31 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_auto_20210528_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
