# Generated by Django 3.1.11 on 2021-05-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_auto_20210531_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
