# Generated by Django 3.1.11 on 2021-05-31 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0016_auto_20210531_0801'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
