# Generated by Django 3.1.11 on 2021-05-31 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('items', '0001_initial'),
        ('trade', '0018_auto_20210531_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='inv_items',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='user',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='item',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='item',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='user',
        ),
        migrations.RemoveField(
            model_name='watchlist',
            name='watchlist_items',
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='item',
        ),
        migrations.RemoveField(
            model_name='watchlistitem',
            name='user',
        ),
        migrations.AlterField(
            model_name='trade',
            name='buyer_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_offer', related_query_name='buyer_offer', to='offers.offer'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='seller_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_offer', related_query_name='seller_offer', to='offers.offer'),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
        migrations.DeleteModel(
            name='Inventory',
        ),
        migrations.DeleteModel(
            name='InventoryItem',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Watchlist',
        ),
        migrations.DeleteModel(
            name='WatchlistItem',
        ),
    ]
