# Generated by Django 3.1.11 on 2021-06-03 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trade', '0019_auto_20210531_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='buyer_trade', related_query_name='buyer_trade', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trade',
            name='seller_offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='seller_offer', related_query_name='seller_offer', to='offers.offer'),
        ),
    ]
