# Generated by Django 3.1.11 on 2021-05-31 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='watchlist_items',
            field=models.ManyToManyField(null=True, to='watchlists.WatchlistItem'),
        ),
    ]
