# Generated by Django 3.1.11 on 2021-05-24 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='deposit',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=8),
        ),
    ]
